### PR TITLE
Handle multiple connections server

### PR DESCRIPTION
**Pull request by JbIPS**
With Hapi 8, inject must be directly on `connection` if there is more than one.
src: [Hapi API - inject](https://github.com/hapijs/hapi/blob/master/API.md#serverinjectoptions-callback)

### CODE REVIEW

**Comment by JbIPS** [comment]
Test server should have one, then two connection for the coverage to be complete. Should I just make a second `setupServer` method but this time with two connections, and redo all the tests with this conf?

**Comment by arlo** [comment]
@cadecairos, is this PR ok for you. We can rebased it if needed.

**Comment by cadecairos** [comment]
@arlo yes, this PR needs a rebase before I can merge it.

**Comment by JbIPS** [comment]
@cadecairos Rebased & ready!

**Comment by JbIPS** [comment]
@cadecairos Could you merge it before I need to rebase it again please ? Thank you

**Pull request merged**
