### PR TITLE
better test for request.payload & payload.requests

### PR DESCRIPTION
**Pull request by catalint**
Better handling for empty payload or requests not being an array

### CODE REVIEW

**Comment by catalint** [comment]
added `Joi` module & validation declaration for route
this makes it easier to identify first-running issues & create automated docs using tools like `hapi-swagger`

**Comment by catalint** [comment]
@cadecairos please take a look over this and tell me what you think

**Comment by catalint** [comment]
bump

**Comment by cadecairos** [comment]
Looks great @catalint, thanks for the Pull Request!

**Pull request merged**
