### PR TITLE
Fixes bug - internals.evalResults now returns `0` when `Hoek.reach(result, path)` evals to `0`.

### PR DESCRIPTION
**Pull request by adisingh007**
Fixed bug on issue number #88 

Added a check in the function `internals.evalResults`to check if the result evaluated is neither `falsy` nor it is equal to `0`, then it returns `{}`. Else it returns the exact result.

### CODE REVIEW

**Comment by Marsup** [comment]
You should check your diff before submitting PRs.

**Comment by adisingh007** [comment]
Hello,
My apologies. I know my previous commit was a mess because of the prettier
plugin I was using in my atom text editor. I have made another commit and
fixed the diff issue. This was my first time contributing to an open source
project.
I have fixed the problem. And now the diff comparison will be seen clearly.

Will for sure take care of it next time.

Regards,
Aditya Singh

**Comment by Marsup** [comment]
Sure, no problem. I'm not sure which commit you're referring to, this PR is closed and it's still the old diff.

**Comment by adisingh007** [comment]
Actually this issue number #89  was opened by mistake. The actual issue number is #88 . Apologies.

**Comment by Marsup** [comment]
There's no PR with that commit though, is there? You're going to need to add some test to cover that bit as well.

**Comment by adisingh007** [comment]
Hello,
Sorry for the confusion. I recreated the PR. The PR number is 91. I am new to contributing to open source. Apologies for the confusion.

**Pull request closed without merging**
