### PR TITLE
hapi 8. Closes #37

### LINKED ISSUE #37: hapi 8.0 API

### PR DESCRIPTION
**Pull request by hueniverse**

### CODE REVIEW

**Comment by phated** [comment]
Is this going to be merged soon?  It is the only plugin we are using that isn't updated to work with hapi 8.

**Comment by nvcexploder** [comment]
yep - working on it now.

**Comment by phated** [comment]
Thanks! :high_five:

**Comment by nvcexploder** [comment]
There's still 2 tests that aren't passing after merge

**Comment by nvcexploder** [comment]
Fixing tests, CLI merging and committing.

**Comment by phated** [comment]
:heart:

**Pull request merged**
