### PR TITLE
Reference value illegal characters check is too restrictive

### PR DESCRIPTION
**Pull request by cameron-normative**
My API uses UUIDs such as "7d18617c-f7b5-4e82-9eaa-beb647630d0c" and the current RegEx is too restrictive.  Allowing dashes makes my case work.

### CODE REVIEW

**Comment by profpylons** [comment]
Hi,
Apologies, I didn't see your pull request before I submitted a very similar one. It could have saved me some debugging time, if I'd noticed!

Hopefully one will make it.

Cheers..Paul

**Comment by cjnqt** [comment]
+1 for this. We are also using UUIDs and cant really use bassmaster now because it is impossible to grab any ID. This PR fixes that.

**Comment by cadecairos** [comment]
I just took a look at the PR that @profpylons submitted. It looks like it supports your use case and more, and includes tests. 

@cameron-normative I'm going to close this PR in favour of that one. Thanks for your contribution, in any case!

**Comment by cadecairos** [comment]
(closed in favour of #75)

**Pull request closed without merging**
